# Generated by Django 5.2.4 on 2025-12-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
